name: Run Python Unit Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # Python 3.12 をセットアップ
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # pip キャッシュを利用
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 仮想環境作成と依存関係インストール
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          # requirements.txt があればそれを使う
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # ユニットテスト実行
      - name: Run Unit Tests
        run: |
          source .venv/bin/activate
          pytest --cov=src --cov-report=term-missing tests/
